spring:
  application:
    name: Ynov Classroom API
  datasource:
    url: "jdbc:h2:file:./target/db/embedded;MODE=POSTGRESQL;AUTO_SERVER=true"
    username: root
    password: root
    driver-class-name: org.h2.Driver
  jpa:
    open-in-view: true
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: create-drop

---
spring.config.activate.on-profile: localhost
DATABASE_USERNAME: root
DATABASE_PASSWORD: root
#spring:
#  datasource:
#    driver-class-name: org.h2.Driver
#  jpa:
#    hibernate:
#      ddl-auto: create-drop
#
#---
#spring.config.activate.on-profile: test
#DATABASE_JDBC_URL: "jdbc:h2:file:./target/db/embedded;MODE=POSTGRESQL;AUTO_SERVER=true"
#DATABASE_USERNAME: root
#DATABASE_PASSWORD: root
#spring:
#  datasource:
#    driver-class-name: org.h2.Driver
#  jpa:
#    hibernate:
#      ddl-auto: create-drop
#
#---
#spring.config.activate.on-profile: prod
#DATABASE_JDBC_URL: "jdbc:postgresql://127.0.0.1:5494/classroom"
#DATABASE_USERNAME: test
#DATABASE_PASSWORD: test
#spring:
#  datasource:
#    driver-class-name: org.postgresql.Driver
#  jpa:
#    database: POSTGRESQL
#    show-sql: false
#    hibernate:
#      ddl-auto: update