openapi: 3.0.1

info:
  title: Ynov Classroom API
  version: 0.0.1
  description: API for ynov classroom web service project
servers:
  - url: http://localhost:8080
    description: Local server

tags:
  - name: subject
  - name: teacher
  - name: student
  - name: admin

paths:
  '/subjects':
    get:
      tags:
        - subject
      summary: List of subject
      description: List of subject
      operationId: listSubjects
      responses:
        '200':
          description: 'Ok'
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Subject'

  '/teachers':
    get:
      tags:
        - teacher
      summary: List of teachers
      description: List of teachers
      operationId: listTeachers
      responses:
        '200':
          description: 'Ok'
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Teacher'

  '/students':
    get:
      tags:
        - student
      summary: List of students
      description: List of students
      operationId: listStudents
      responses:
        '200':
          description: 'Ok'
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Student'

  '/admin/login':
    post:
      tags:
        - admin
      summary: Login into admin
      description: Login into admin
      operationId: loginAdmin
      parameters:
        - in: query
          name: login
          content:
            application/json:
              schema:
                type: string
                example: "username"
        - in: query
          name: password
          content:
            application/json:
              schema:
                type: string
                example: "password"
      responses:
        '200':
          description: 'Ok'
          content:
            application/json:
              schema:
                type: string
                example: "40e6215d-b5c6-4896-987c-f30f3678f608"
        '401':
          description: 'Unauthorized'

  '/admin/subjects':
    post:
      tags:
        - subject
      summary: Save new subject
      description: Save new subject
      operationId: saveSubject
      parameters:
        - in: header
          name: Authorization
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewSubject'
      responses:
        '200':
          description: 'Ok'
        '401':
          description: 'Unauthorized'

  '/admin/teachers':
    post:
      tags:
        - teacher
      summary: Save new teacher
      description: Save new teacher
      operationId: saveTeacher
      parameters:
        - in: header
          name: Authorization
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewTeacher'
      responses:
        '200':
          description: 'Ok'
        '401':
          description: 'Unauthorized'

  '/admin/students':
    post:
      tags:
        - student
      summary: Save new student
      description: Save new student
      operationId: saveStudent
      parameters:
        - in: header
          name: Authorization
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewStudent'
      responses:
        '200':
          description: 'Ok'
        '401':
          description: 'Unauthorized'

components:
  schemas:
    Subject:
      type: object
      properties:
        id:
          type: integer
        subject:
          type: string
    Teacher:
      type: object
      properties:
        id:
          type: integer
        firstname:
          type: string
        lastname:
          type: string
        subject:
          type: integer
        level:
          type: integer
    Student:
      type: object
      properties:
        id:
          type: integer
        firstname:
          type: string
        lastname:
          type: string
    NewSubject:
      type: object
      properties:
        subject:
          type: string
    NewTeacher:
      type: object
      properties:
        firstname:
          type: string
        lastname:
          type: string
        subject:
          type: integer
        level:
          type: integer
    NewStudent:
      type: object
      properties:
        firstname:
          type: string
        lastname:
          type: string
