openapi: 3.0.1

info:
  title: Ynov Classroom API
  version: 0.0.1
  description: API for ynov classroom web service project
servers:
  - url: http://localhost:8080
    description: Local server

tags:
  - name: classroom
  - name: teacher
  - name: student
  - name: admin

paths:
  '/classrooms':
    get:
      tags:
        - classroom
      summary: List of classrooms
      description: List of classrooms
      operationId: listClassrooms
      responses:
        '200':
          description: 'Ok'
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Classroom'
  '/teachers':
    get:
      tags:
        - teacher
      summary: List of teachers
      description: List of teachers
      operationId: listTeachers
      responses:
        '200':
          description: 'Ok'
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Teacher'
  '/students':
    get:
      tags:
        - student
      summary: List of students
      description: List of students
      operationId: listStudents
      responses:
        '200':
          description: 'Ok'
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Student'
  '/admin/login':
    post:
      tags:
        - admin
      summary: Login into admin
      description: Login into admin
      operationId: loginAdmin
      parameters:
        - in: query
          name: login
          content:
            application/json:
              schema:
                type: string
                example: "username"
        - in: query
          name: password
          content:
            application/json:
              schema:
                type: string
                example: "1234"

      responses:
        '200':
          description: 'Ok'
          content:
            application/json:
              schema:
                type: string
                example: "40e6215d-b5c6-4896-987c-f30f3678f608"
        '401':
          description: 'Unauthorized'
  '/admin/classrooms':
    post:
      tags:
        - classroom
      summary: Save new classroom
      description: Save new classroom
      operationId: saveClassroom
      parameters:
        - in: header
          name: Authorization
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewClassroom'
      responses:
        '200':
          description: 'Ok'
        '401':
          description: 'Unauthorized'
  '/admin/teachers':
    post:
      tags:
        - teacher
      summary: Save new teacher
      description: Save new teacher
      operationId: saveTeacher
      parameters:
        - in: header
          name: Authorization
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewTeacher'
      responses:
        '200':
          description: 'Ok'
        '401':
          description: 'Unauthorized'
  '/admin/students':
    post:
      tags:
        - student
      summary: Save new student
      description: Save new student
      operationId: saveStudent
      parameters:
        - in: header
          name: Authorization
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewStudent'
      responses:
        '200':
          description: 'Ok'
        '401':
          description: 'Unauthorized'

components:
  schemas:
    Classroom:
      type: object
      properties:
        id:
          type: integer
        level:
          type: integer
        section:
          type: string
    Teacher:
      type: object
      properties:
        id:
          type: integer
        firstname:
          type: string
        lastname:
          type: string
        sector:
          type: integer
    Student:
      type: object
      properties:
        id:
          type: integer
        firstname:
          type: string
        lastname:
          type: string
    NewClassroom:
      type: object
      properties:
        level:
          type: integer
        section:
          type: string
    NewTeacher:
      type: object
      properties:
        firstname:
          type: string
        lastname:
          type: string
        sector:
          type: integer
    NewStudent:
      type: object
      properties:
        firstname:
          type: string
        lastname:
          type: string
